services:
  app:
    build: .
    container_name: node_ddd
    ports:
      - "3000:3000"
    volumes:    
      - ./app/src:/usr/src/app/src
      - ./app/tsconfig.json:/usr/src/app/tsconfig.json
    command: npm run dev
    environment:
      - NODE_ENV=development